export type KioskFlow =
  | 'HOME'
  | 'BOOKING_SEARCH'
  | 'BOOKING_CONFIRM'
  | 'PATIENT_CONTEXT_SEARCH'
  | 'PATIENT_CONTEXT_CONFIRM'
  | 'BIOMETRIC_VERIFY'
  | 'WALKIN_SEARCH'
  | 'WALKIN_SELECT_PATIENT'
  | 'WALKIN_SELECT_SERVICE'
  | 'WALKIN_CONFIRM'
  | 'REGISTRATION_SUCCESS'
  | 'FAILURE'
  | 'ASSISTANCE_QUEUE'

export const FLOW_TRANSITIONS: Record<KioskFlow, readonly KioskFlow[]> = {
  HOME: ['BOOKING_SEARCH', 'WALKIN_SEARCH'],
  BOOKING_SEARCH: ['BOOKING_CONFIRM', 'PATIENT_CONTEXT_SEARCH', 'FAILURE'],
  BOOKING_CONFIRM: ['BIOMETRIC_VERIFY', 'REGISTRATION_SUCCESS', 'FAILURE'],
  PATIENT_CONTEXT_SEARCH: ['PATIENT_CONTEXT_CONFIRM', 'FAILURE'],
  PATIENT_CONTEXT_CONFIRM: ['WALKIN_SELECT_SERVICE', 'HOME'],
  BIOMETRIC_VERIFY: ['REGISTRATION_SUCCESS', 'FAILURE'],
  WALKIN_SEARCH: ['WALKIN_SELECT_PATIENT', 'FAILURE'],
  WALKIN_SELECT_PATIENT: ['WALKIN_SELECT_SERVICE', 'WALKIN_SEARCH', 'FAILURE'],
  WALKIN_SELECT_SERVICE: ['WALKIN_CONFIRM', 'WALKIN_SEARCH', 'FAILURE'],
  WALKIN_CONFIRM: ['BIOMETRIC_VERIFY', 'REGISTRATION_SUCCESS', 'WALKIN_SEARCH', 'FAILURE'],
  REGISTRATION_SUCCESS: ['HOME'],
  FAILURE: ['ASSISTANCE_QUEUE'],
  ASSISTANCE_QUEUE: ['HOME'],
}

export function canTransition(from: KioskFlow, to: KioskFlow): boolean {
  return FLOW_TRANSITIONS[from].includes(to)
}
