export type KioskFlow =
  | 'HOME'
  | 'BOOKING_SEARCH'
  | 'BOOKING_CONFIRM'
  | 'PATIENT_CONTEXT_SEARCH'
  | 'PATIENT_CONTEXT_CONFIRM'
  | 'WALKIN_SELECT_GUARANTEE'
  | 'BIOMETRIC_VERIFY'
  | 'BPJS_SELECT_REFERENCE'
  | 'WALKIN_SELECT_SERVICE'
  | 'WALKIN_CONFIRM'
  | 'REGISTRATION_SUCCESS'
  | 'REGISTRATION_REPRINT'
  | 'FAILURE'
  | 'ASSISTANCE_QUEUE'

export const FLOW_TRANSITIONS: Record<KioskFlow, readonly KioskFlow[]> = {
  HOME: [
    'BOOKING_SEARCH',
    'BOOKING_CONFIRM',
    'PATIENT_CONTEXT_SEARCH',
    'PATIENT_CONTEXT_CONFIRM',
    'REGISTRATION_REPRINT',
    'FAILURE',
  ],
  BOOKING_SEARCH: [
    'BOOKING_CONFIRM',
    'PATIENT_CONTEXT_SEARCH',
    'PATIENT_CONTEXT_CONFIRM',
    'REGISTRATION_REPRINT',
    'FAILURE',
  ],
  BOOKING_CONFIRM: ['BIOMETRIC_VERIFY', 'BPJS_SELECT_REFERENCE', 'REGISTRATION_SUCCESS', 'FAILURE'],
  PATIENT_CONTEXT_SEARCH: ['PATIENT_CONTEXT_CONFIRM', 'REGISTRATION_REPRINT', 'FAILURE'],
  PATIENT_CONTEXT_CONFIRM: ['WALKIN_SELECT_GUARANTEE', 'FAILURE', 'HOME'],
  WALKIN_SELECT_GUARANTEE: [
    'WALKIN_SELECT_SERVICE',
    'BIOMETRIC_VERIFY',
    'BPJS_SELECT_REFERENCE',
    'FAILURE',
    'HOME',
  ],
  BIOMETRIC_VERIFY: [
    'BPJS_SELECT_REFERENCE',
    'REGISTRATION_SUCCESS',
    'WALKIN_SELECT_SERVICE',
    'FAILURE',
  ],
  BPJS_SELECT_REFERENCE: ['REGISTRATION_SUCCESS', 'WALKIN_SELECT_SERVICE', 'FAILURE', 'HOME'],
  WALKIN_SELECT_SERVICE: ['WALKIN_CONFIRM', 'FAILURE'],
  WALKIN_CONFIRM: ['BIOMETRIC_VERIFY', 'REGISTRATION_SUCCESS', 'FAILURE'],
  REGISTRATION_SUCCESS: ['HOME'],
  REGISTRATION_REPRINT: ['HOME'],
  FAILURE: ['ASSISTANCE_QUEUE'],
  ASSISTANCE_QUEUE: ['HOME'],
}

export function canTransition(from: KioskFlow, to: KioskFlow): boolean {
  return FLOW_TRANSITIONS[from].includes(to)
}
